<a href="https://colab.research.google.com/github/Ashok-nimmala/GENERATIVE-AI/blob/main/ASS_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.Write Python code from scratch to find error metrics of deep learning model. Actual values and deep learning model predicted values are shown in Table 1. Also compare the results with the outcomes of libraries

In [1]:
from sklearn.metrics import mean_absolute_error

Y_actual = [20, 30, 40, 50, 60]
Y_pred = [20.5, 30.3, 40.2, 50.6, 60.7]


MAE= mean_absolute_error(Y_actual, Y_pred)

print(f"Mean Absolute Error : {MAE:.2f}")

Mean Absolute Error : 0.46


In [2]:
from sklearn.metrics import mean_squared_error

MSE= mean_squared_error(Y_actual, Y_pred)
print(f"Mean Squared Error : {MSE:.2f}")

Mean Squared Error : 0.25


In [3]:
import numpy as np

rmse_numpy = np.sqrt(np.mean((np.array(Y_actual) - np.array(Y_pred)) ** 2))
print(f"RMSE using NumPy: {rmse_numpy:.4f}")

RMSE using NumPy: 0.4960


QUESTION 2

Write python code from scratch to find evaluation metrics of deep learning model. Actual values and deep learning model predicted values are shown in Table 2. Also compare the results with outcome of libraries

In [4]:
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

y_actual = [0, 0, 1, 1, 2, 0, 0, 0, 1, 0, 2, 0, 0, 1, 1, 2, 2, 1, 0, 2, 1, 0, 2, 2, 0, 2, 1, 2, 2, 2]
y_pred =   [0, 0, 1, 0, 2, 0, 0, 0, 1, 2, 2, 0, 0, 1, 1, 2, 2, 1, 2, 2, 1, 0, 2, 2, 0, 2, 1, 2, 2, 2]

cm = confusion_matrix(y_actual, y_pred)

print("Confusion Matrix :\n", cm)

Confusion Matrix :
 [[ 9  0  2]
 [ 1  7  0]
 [ 0  0 11]]


In [5]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_actual, y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")

Accuracy: 90.00%


In [6]:
from sklearn.metrics import precision_score

precision = precision_score(y_actual, y_pred, average='macro')
print(f"Precision: {precision:.2f}")

Precision: 0.92


In [7]:
from sklearn.metrics import f1_score

f1 = f1_score(y_actual, y_pred, average='weighted')
print(f"F1-Score {f1:.2f}")

F1-Score 0.90


In [8]:
from sklearn.metrics import recall_score

recall = recall_score(y_actual, y_pred, average='weighted')
print("Recall:", recall)

Recall: 0.9
